// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return ball.init();
  });

  window.ball = {
    duration: 2200,
    scaleVal: "scale(0.7)",
    init: function() {
      this.swayWrapper = $(".sway-wrapper");
      this.el = $(".floater-wrapper");
      this.text = this.el.find(".text");
      this.testText = $(".test-text-el");
      this.pickPosition();
      return setInterval((function(_this) {
        return function() {
          return _this.pickPosition();
        };
      })(this), this.duration);
    },
    pickPosition: function() {
      var left, sway, top;
      sway = 13;
      top = Math.random() * sway - sway / 2;
      left = Math.random() * sway - sway / 2;
      return this.swayWrapper.css("transform", "translate(" + top + "px, " + left + "px)");
    },
    fadeOut: function() {
      this.el.addClass("fade-out");
      return this.el.css("transform", "" + (this.randomSkew()) + " " + this.scaleVal);
    },
    fadeIn: function(text) {
      var textHeight, textMargin;
      this.el.addClass("no-transition");
      this.el.css("transform", "" + (this.randomSkew()) + " " + this.scaleVal);
      this.el.css("transform");
      this.el.removeClass("no-transition");
      if (text != null) {
        textHeight = this.getTextHeight(text);
        textMargin = this.scale(textHeight, 29, 87, 25, 0);
        this.text.css("marginTop", textMargin);
      }
      this.el.removeClass("fade-out");
      return this.el.css("transform", "skew(0, 0) scale(1)");
    },
    setText: function(text) {
      this.fadeOut();
      return setTimeout((function(_this) {
        return function() {
          _this.text.text(text);
          return _this.fadeIn(text);
        };
      })(this), this.duration * 1.5);
    },
    randomSkew: function() {
      var skew1, skew2, skewMax;
      skewMax = 20;
      skew1 = Math.random() * skewMax - skewMax / 2;
      skew2 = Math.random() * skewMax - skewMax / 2;
      return "skew(" + skew1 + "deg, " + skew2 + "deg)";
    },
    getTextHeight: function(text) {
      this.testText.text(text);
      return this.testText.height();
    },
    scale: function(input, inMin, inMax, outMin, outMax) {
      var percent;
      if (input < inMin) {
        input = inMin;
      }
      if (input > inMax) {
        input = inMax;
      }
      percent = ((input - inMin) * 100) / (inMax - inMin);
      return percent * ((outMax - outMin) / 100) + outMin;
    }
  };

}).call(this);